# client netlify.toml
[build]
  command = "yarn run build"
  functions = "./netlify/functions/handlers"
  publish = "build"

[build.environment]
  APP_SPECIFIC_FLAG = "true"
  
  [dev]
  targetPort = 3000